#!/sbin/busybox sh

export BOOTREC_CACHE_NODE="/dev/block/mmcblk0p14 b 179 14"
export BOOTREC_CACHE="/dev/block/mmcblk0p14"
export BOOTREC_EVENT_NODE="/dev/input/event8 c 13 72"
export BOOTREC_EVENT="/dev/input/event8"
export BOOTREC_LED_RED="/sys/class/leds/pwr-red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/pwr-green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/pwr-blue/brightness"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p11 b 179 11"
export BOOTREC_FOTA="/dev/block/mmcblk0p11"
export BOOTREC_VIBRATOR="/sys/class/timed_output/vibrator/enable"
